[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "MARS Coding Tutorial"
authors = [{name = "Christopher Jacobs", email = "clj00009@mix.wvu.edu"}]
dynamic = ["version", "description"]

